/**
* $themeColor, $themeColorDarken, $textOnThemeColor, $linkOnThemeColor, $linkHoverOnThemeColor
*/

/**
* Background color
*/
.time-countdown-slide .time-ranger .time-pass,
.header-mobile .mobile-top,.background-color-theme,
.sm-notfound .back2home,
.bonus-title:before,
.about-container .our-member .image-content .member-social li a:hover,
.contact-us-info .contact-social li a:hover,
.w-newsletter .action-newsletter button,
.bottom-product-slider .block-title strong:before,
.product-info-main .product-social-links .action:hover, .product-info-main .product-addto-links .action:hover,
.product-info-main .box-tocart .action.tocart, .product-options-bottom .box-tocart .action.tocart,

.post-content .post-description .post-info-blog .post-read-more:hover,

.sidebar .block .block-title,
#price-slider .ui-slider-range,
#price-slider .ui-slider-handle,
.product-1-style .products-grid .product-item-info:hover .product-item-details .product-item-actions .actions-primary .tocart,
.product-1-style .products-grid .product-item-info .product-item-details .product-item-actions .actions-primary .tocart,
.product-2-style .products-grid .product-item-info .product-item-details .product-item-actions .actions-primary .tocart,
.product-1-style .products-grid .product-item-info .image-product .quickview-handler:hover,
.product-2-style .products-grid .product-item-info .image-product .quickview-handler:hover,
.vertical-menu-block .sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu>li.sm_megamenu_actived>a.sm_megamenu_head, 
.vertical-menu-block .sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu>li:hover>a.sm_megamenu_head,
.products-list .product-item-info .image-product .quickview-handler:hover,

.group-deal-1 .product-item-info .product-item-details .product-item-actions .actions-primary .tocart:hover,
.group-deal-1 .product-item-info .product-item-details .product-item-actions .actions-secondary .action:hover,

.social-footer ul li a:hover,
.footer-1-style .subcribe-footer-content .block-subscribe-footer .action-button button,

.header-style-1 .form.minisearch .actions button,
.header-style-1 .vertical-menu-block .block-title-menu,
.cms-index-index .header-style-1 .horizontal-megamenu-block .sm_megamenu_menu > li.home-item > a:before,
.header-style-1 .horizontal-megamenu-block .sm_megamenu_menu > li:hover > a:before,
.header-style-1 .horizontal-megamenu-block .sm_megamenu_menu > li.sm_megamenu_actived > a:before,
.header-style-1 .header-wishlist a span,
.header-style-1.header-container .minicart-wrapper .action.showcart .counter .counter-number,
.header-style-2 .header-wishlist a span,
.header-style-2.header-container .minicart-wrapper .action.showcart .counter .counter-number,
.listingtab-style-1 .sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li.tab-sel,
.listingtab-style-1 .sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li:hover,
.header-style-2 .form.minisearch .actions button,
.header-style-2 .vertical-menu-block .block-title-menu,
.header-style-2 .horizontal-block .promotion-block a:hover,
.title-style-2 .block .block-title strong:after,
.post-slider-1 .info-post .post-read-more a:hover,
.listingtab-style-2 .ltabs-tabs-container .ltabs-tabs li:after,
.listingtab-style-2 .ltabs-tabs-container .ltabs-tabs li:before,
.listingtab-style-2 .owl-theme .owl-dots .owl-dot:hover span,
.listingtab-style-2 .owl-theme .owl-dots .owl-dot.active span,
.client-newletters .our-client-say .owl-theme .owl-dots .owl-dot:hover span,
.client-newletters .our-client-say .owl-theme .owl-dots .owl-dot.active span,
.newltters-v2 .block-subscribe-footer .action-button button,
.about-client-say .item:before{
background-color: #<?php echo $themeColor; ?>;
}

.text-branner .hot-item:after{
border-bottom: 63px solid #<?php echo $themeColor; ?>;
}


/**
* Border color
*/
.default-style .resp-tabs-list li.active,
.default-style .resp-tabs-list li:hover,
.block-brands-2 .item:hover,
.list-slider-1 .product-type-list .image-product:hover,
.slider-categories-1 .block-categories .cat-wrap-slider .item .content-box:hover,
.group-product-slider-1 .block-content .slider-thumbs .slick-current .item-thumb,
.footer-1-style .block-footer-title:after,.footer-2-style .block-footer-title:after,.block-footer .block-footer-content ul li a:hover,
.group-product-slider .item-inner .product-item-details .deals-countdown .deals-time .num-time,
.group-product-slider .item-inner .image-thumbs .thumbs-product .item-img.thumb-active,
.group-product-slider .item-inner .image-thumbs .thumbs-product .item-img:hover,
.block-slider-post .item .info-post .post-read-more a:hover,
.products-deals .products-grid .product-item-info .deals-countdown .deals-time,
.fotorama__thumb-border{
border-color: #<?php echo $themeColor; ?>;
}

/**
* Background color and border color
*/

.modes .modes-mode:hover,
.modes .modes-mode.active,
.pages .item:hover,
.pages .item.current,

.nav-style-1 .owl-theme .owl-nav [class*="owl-"]:hover,
.nav-style-2 .owl-theme .owl-nav [class*="owl-"]:hover,
.group-product-slider-1 .slick-prev:hover, .group-product-slider-1 .slick-next:hover,
.product-1-style .products-grid .product-item-info .product-item-details .product-item-actions .actions-secondary .action:hover,
.product-2-style .products-grid .product-item-info .product-item-details .product-item-actions .action:hover,
.products-list .product-item-info .product-item-details .product-item-actions .actions-primary .tocart:hover,
.products-list .product-item-info .product-item-details .product-item-actions .actions-secondary .action:hover,
.socials-popup ul li a:hover,
.about-policy .item:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
}

.gallery-placeholder .fotorama__thumb__arr:hover,
.group-product-slider .item-inner .product-item-details .product-item-actions .actions-primary .tocart:hover,
.listingtab-style-list .products-grid .product-item-info .product-item-details .product-item-actions .actions-primary .tocart:hover,
.product-info-main .product-addto-links .action:hover{
background-color: #<?php echo $themeColor; ?>!important;
border-color: #<?php echo $themeColor; ?>!important;
}

/**
* Background darken color
*/

.w-newsletter .action-newsletter button:hover,
.product-1-style .products-grid .product-item-info .product-item-details .product-item-actions .actions-primary .tocart:hover,
.art-style-1 .smas-btn .btn.btn-search:hover,
.text-branner .text-offer .explorer:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

/**
* Link hover color
*/
.post-content.post-custom .post-description .post-title a:hover,
.mega-feature-content ul li a:hover,
.minicart-wrapper .minicart-items .product-item-name a:hover,

.sidebar .block.filter .filter-options .filter-options-content ol li a:hover,
.block-cat-1 .child-cat .sub-cats li a:hover,
{
color: #<?php echo $linkHoverColor; ?>;
}

.block-cat-1 .child-cat .sub-cats li a:hover:before{
background-color: #<?php echo $linkHoverColor; ?>;
}

/**
* Text theme color
*/

.text-theme-color,
.contact-us-info .info-contact li:before,
.header-style-1 .language-currency .switcher .switcher-content:hover .action-switcher,
.block-footer .footer-contact ul li:before,.footer-bottom address a,
.cms-index-index .header-style-1 .horizontal-megamenu-block .sm_megamenu_menu > li.home-item > a,
.header-style-1 .horizontal-megamenu-block .sm_megamenu_menu > li:hover > a,
.header-style-1 .horizontal-megamenu-block .sm_megamenu_menu > li.sm_megamenu_actived > a,
.header-style-1 .header-wishlist a:hover:before, .header-style-1.header-container .minicart-wrapper .action.showcart:hover:after,
.header-style-1.header-container .minicart-wrapper .action.showcart:hover,
.header-style-1.header-container .minicart-wrapper .action.showcart:hover .text,
.customer-action:hover .toplinks-wrapper:after, .customer-action:hover .customer-links > span,
.header-style-1 .header-top .header-topleft ul li:before,
.header-style-1 .header-top .social-top ul li a:hover,
.group-product-slider .item-inner .product-item-details .deals-countdown .deals-time .num-time,
.block-footer .block-footer-content ul li a:hover,
.block-slider-post .item .info-post .post-title a:hover,
.cms-index-index .header-style-2 .horizontal-megamenu-block .sm_megamenu_menu > li.home-item > a,
.header-style-2 .horizontal-megamenu-block .sm_megamenu_menu > li:hover > a,
.header-style-2 .horizontal-megamenu-block .sm_megamenu_menu > li.sm_megamenu_actived > a,
.header-style-2.header-container .minicart-wrapper .action.showcart .price-minicart,
.header-style-2 .email-header:before, .header-style-2 .email-header a:hover,
.products-deals .products-grid .product-item-info .deals-countdown .deals-time .num-time,
.our-client-say .item .client-info:after,
.customer-action ul.header.links li a:hover,
.mega-feature-content ul li a:hover,
.post-holder .post-header .post-info .value,
.post-holder .post-header .post-info .value a,
.post-content.post-custom .post-description .post-title a:hover,
.about-top a.lear-more:hover,
.product.data.items.accordion-style .item.title.resp-accordion.active a,
.product.data.items.accordion-style .item.title.resp-accordion:hover a,
.default-style .resp-tabs-list li.active a,
.default-style .resp-tabs-list li:hover a,
.vertical-style .resp-tabs-list li.active a,
.vertical-style .resp-tabs-list li:hover a,
.product-2-style .price-box .special-price .price,.product-2-style .price-box .price,
.nav-style-3 .owl-theme .owl-nav [class*="owl-"]:hover{ 
color: #<?php echo $themeColor; ?>;
}


/**
* Text on theme color
*/
.sidebar .block .block-title strong,
.sidebar .block.filter .block-title.filter-title:before,
.about-container .our-member .image-content .member-social li a:hover,
.contact-us-info .contact-social li a:hover,
.post-content.post-custom .post-description .post-info-blog .post-read-more:hover,
.header-style-1 .vertical-menu-block .block-title-menu,
.header-style-1 .block-search .form.minisearch .actions button,
.header-style-2 .block-search .form.minisearch .actions button,
.nav-style-1 .owl-theme .owl-nav [class*="owl-"]:hover,
.nav-style-2 .owl-theme .owl-nav [class*="owl-"]:hover,
.art-style-1 .smas-btn .btn.btn-search,
.footer-1-style .subcribe-footer-content .block-subscribe-footer .action-button button,
.social-footer ul li a:hover,
.post-slider-1 .info-post .post-read-more a:hover,
.modes .modes-mode:hover,
.modes .modes-mode.active,
.pages .item:hover a,
.pages .item.current strong,
.product-1-style .products-grid .product-item-info .image-product .quickview-handler:hover,
.product-1-style .products-grid .product-item-info:hover .product-item-details .product-item-actions .actions-primary .tocart,
.product-1-style .products-grid .product-item-info .product-item-details .product-item-actions .actions-secondary .action:hover,

.group-deal-1 .timer-content,
.group-deal-1 .product-item-info .product-item-details .product-item-actions .actions-primary .tocart:hover,
.group-deal-1 .product-item-info .product-item-details .product-item-actions .actions-secondary .action:hover,
.text-branner .hot-item,
.text-branner .text-offer .explorer,
.listingtab-style-1 .sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li.tab-sel,
.listingtab-style-1 .sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li:hover{
color: #<?php echo $textOnThemeColor; ?>;
}

.pages .item:hover .action:before,
.product-info-main .box-tocart .action.tocart,
.product-options-bottom .box-tocart .action.tocart,
.product-info-main .product-social-links .action:hover,
.product-info-main .product-addto-links .action:hover,
.group-product-slider-1 .block-title strong,
.group-product-slider-1 .slick-prev:hover, .group-product-slider-1 .slick-next:hover{
color: #<?php echo $textOnThemeColor; ?>!important;
}

.header-mobile .mobile-menu > a span{
background-color: #<?php echo $textOnThemeColor; ?>;
}

.minicart-mobile .minicart-wrapper .action.showcart:before{
color: #<?php echo $textOnThemeColor; ?>;
}


/**
* Link on theme color
*/
.vertical-menu-block .sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu>li.sm_megamenu_actived>a.sm_megamenu_head, 
.vertical-menu-block .sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu>li:hover>a.sm_megamenu_head,
.vertical-menu-block .sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu>li.sm_megamenu_actived>a.sm_megamenu_head span:before, 
.vertical-menu-block .sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu>li:hover>a.sm_megamenu_head span:before{
	color: #<?php echo $linkOnThemeColor; ?>;
}

/**
* Link hover on theme color
*/

