<div id="buy-now-modal">
    <div class="modal-inner-content">
        <form action="<?= $block->getUrl('buy_now/place/order');?>" method="post" id="bay-now-form" enctype="multipart/form-data" autocomplete="off" data-mage-init='{"validation":{}}' data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
            <div class="field firstname required">
                <label for="firstname" class="label"><?= $block->escapeHtmlAttr(__('First Name')) ?></label>
                <div class="control">
                    <input type="text" name="firstname" id="firstname" value="" title="First Name" class="required-entry input-text" />
                </div>
            </div>
            <div class="field lastname required">
                <label for="lastname" class="label"><?= $block->escapeHtmlAttr(__('Last Name')) ?></label>
                <div class="control">
                    <input type="text" name="lastname" id="lastname" value="" title="Last Name" class="required-entry input-text" />
                </div>
            </div>

            <label for="telephone"><?= $block->escapeHtmlAttr(__('Phone Number')) ?></label>
            <input placeholder="+38 0ХХ-ХХХ-ХХ-ХХ" data-validate="{required:true, 'validate-phone':true}" name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="" class="input-text required validate-phone" type="text" />
        </form>

    </div>
</div>

<div id="result-success-buy-now-modal">
    <div class="modal-inner-content">
        <p><?= $block->escapeHtml(__('Order placed successfully.')) ?></p>
    </div>
</div>

<div id="result-fail-buy-now-modal">
    <div class="modal-inner-content">
        <p><?= $block->escapeHtml(__('Something went wrong, try again later.')) ?></p>
    </div>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal',
            'imask'
        ],
        function($, modal, imask) {
            IMask(
                document.getElementById('telephone'),
                {
                    mask: '+38 000-000-00-00'
                }
            );

            var resultOptions = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                modalClass: 'buy-now-modal',
                title: $.mage.__('Buy Now'),
                buttons: [{
                    text: $.mage.__('Close'),
                    class: 'action',
                    click: function (e) {
                        this.closeModal();
                    }
                }]
            };

            modal(resultOptions, $('#result-success-buy-now-modal'));
            modal(resultOptions, $('#result-fail-buy-now-modal'));

            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                modalClass: 'buy-now-modal',
                title: $.mage.__('Buy Now'),
                buttons: [{
                    text: $.mage.__('Submit'),
                    class: 'action buy_now_submit_button',
                    click: function (e) {
                        if (!$('#bay-now-form').valid()) {
                            return;
                        }
                        var formData = $("#bay-now-form").serializeArray();
                        var postData = JSON.parse(e.currentTarget.getAttribute('data-buynow'));

                        for ( var key in postData ) {
                            formData.push({name: key, value: postData[key]});
                        }

                        jQuery.ajax({
                            url: "<?= $block->getUrl('buy_now/place/order');?>",
                            type: 'POST',
                            data : $.param(formData),
                            success: function(response){
                                var modalSelector = '';
                                if (response.success) {
                                    modalSelector = '#result-success-buy-now-modal';
                                } else {
                                    modalSelector = '#result-fail-buy-now-modal';
                                }

                                $(modalSelector).modal("openModal");
                            },
                            error: function(result){
                                console.log('no response !');
                            }
                        });

                        this.closeModal();
                    }
                }]
            };

            modal(options, $('#buy-now-modal'));
            $(".buynow").on('click',function() {
                $("#buy-now-modal").modal("openModal");

                $('.buy_now_submit_button').attr('data-buynow', $(this).attr('data-buynow'));
            });
        }
    );
</script>
<style>
    .modal-slide.buy-now-modal{ width: 30%;     left: 35%; }
</style>
