<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
    $_posts = $block->getPost() ;
    $width = 80;
    $height = 60;
    $imageHelper = $this->helper(\Magefan\Blog\Helper\Image::class);
    ?>
<?php if ($_postCollection->count()) { ?>
<div class="post-list-wrapper blog-widget-recent block-footer">
<div class="block-footer-title">
    <?php echo $block->escapeHtml($block->getTitle()) ?>
 </div>   
    <div class="post-list clearfix">
        <?php foreach ($_postCollection as $_post) { ?>
            <?php
                $_postUrl = $_post->getPostUrl();
                $_postName = $block->escapeHtml($_post->getTitle(), null, true);
            ?>
          

                    <div class="item clearfix">
                         
                        <div class="image-post">
                            <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                                <img src="<?php echo $imageHelper->init($_post->getFeaturedImg())->resize($width, $height); ?>" alt="<?php echo $_postName ?>"  >
                            </a>
                           
                        </div>
                       
                        <div class="post-text-hld clearfix">
                                 
                                <div class="post-title">
                                        <a class="post-item-link"
                                           href="<?php echo $_postUrl ?>">
                                            <?php echo $_postName; ?>
                                        </a>
                                </div>
                                 <div class="date">
                                    <?php echo $_post->getPublishDate('Y-m-d') ?>
                                </div>
                               
                        </div>
                       
                    </div>

        <?php } ?>
    </div>
</div>
<?php } ?>